name: eval
channels:
  - conda-forge
  - pytorch
  - nvidia
dependencies:
  - python>=3.9,<3.11
  - transformers>=4.25.1
  - accelerate>=0.13.2
  - datasets>=2.6.1
  - evaluate>=0.3.0
  - mosestokenizer=1.0.0
  - huggingface_hub>=0.11.1
  - fsspec>=2023.12.2
  - pytorch-cuda=12.1
  - docker-py
  - streamlit
  - pytest
  - pip:
      - pyext==0.5